# Generated by Django 5.2.6 on 2025-09-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
