# Generated by Django 4.2.14 on 2025-10-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_balance_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='is_temporary_access',
            new_name='allow_temporary_access',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='temp_duration_days',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='temporary_days',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
