# Generated by Django 4.2.14 on 2025-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_is_temporary_access_dictionary_allow_temporary_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='cover_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='dictionaries/covers/'),
        ),
    ]
