# Generated by Django 4.2.14 on 2025-11-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dictionary_cover_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AddField(
            model_name='user',
            name='notification_hour',
            field=models.IntegerField(default=9, help_text='Час для отправки уведомления (0-23).'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_minute',
            field=models.IntegerField(default=0, help_text='Минута для отправки уведомления (0-59).'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=False, help_text='Включены ли уведомления для напоминания об учёбе.'),
        ),
    ]
