# Generated by Django 4.2.14 on 2025-11-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_purchase_options_user_notification_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='api.dictionary')),
                ('learned_words', models.ManyToManyField(blank=True, related_name='learned_by_users', to='api.word')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс изучения',
                'verbose_name_plural': 'Прогресс изучения',
                'indexes': [models.Index(fields=['user', 'dictionary'], name='api_learnin_user_id_a9ada9_idx')],
                'unique_together': {('user', 'dictionary')},
            },
        ),
    ]
